### ISSUE TITLE
Command line app throws an error

### ISSUE THREAD

**Issue by netsensei** [thisismattmiller/viaf-wrapper#1]
Hi,

I've installed the viaf package globally per the installation instructions.

```
/usr/local/bin/viaf -> /usr/local/lib/node_modules/viaf-wrapper/viaf.js
viaf-wrapper@0.1.2 /usr/local/lib/node_modules/viaf-wrapper
├── q@1.4.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── xml2js@0.4.8 (sax@0.6.1, xmlbuilder@3.1.0)
└── request@2.55.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, tunnel-agent@0.4.1, oauth-sign@0.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.4.2, tough-cookie@2.2.0, mime-types@2.0.14, combined-stream@0.0.7, hawk@2.3.1, http-signature@0.10.1, form-data@0.2.0, bl@0.9.4, har-validator@1.8.0)
```

However, when I execute the example `viaf searchPreferredName "Jack Kerouac"` command, I get this error:

```
/usr/local/lib/node_modules/viaf-wrapper/viaf.js:213
    if (program.limit.toLowerCase()){
                     ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/viaf-wrapper/viaf.js:213:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

Doing this works however: `viaf searchPreferredName "Jack Kerouac" --limit Getty`

Suggesting: the limit option should either be just that: optional, or a sensible error message should be thrown.

**Comment by thisismattmiller** [comment]
Sorry, I some how completely missed this issue when you submitted it. This is now fixed. Thanks!
